// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwtapujztvojlkefxpzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3dGFwdWp6dHZvamxrZWZ4cHpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2Mjk1NjAsImV4cCI6MjA2NTIwNTU2MH0.XPnRXrHFEBGiV2UQdNX-migMiyvI_6vqC8tsmh81ZhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);